export const TYPES = {
    IMAGES_LOADED: 'IMAGES_LOADED',
    IMAGE_CLICK: 'IMAGE_CLICK',
    LOADING_STARTED: 'LOADING_STARTED',
    LOADING_FINISHED: 'LOADING_FINISHED',
    IMAGE_SELECTED: 'IMAGE_SELECTED',
    MODAL_CLOSED: 'MODAL_CLOSED'
}